### ISSUE TITLE
Support Destructurama

### ISSUE THREAD

**Issue by luizbon** [RehanSaeed/Serilog.Exceptions#268]
Some custom exceptions can have sensitive data.

It would be nice if was possible to get the benefit of https://github.com/destructurama/attributed destructuring when logging those exceptions.

**Comment by RehanSaeed** [comment]
Looked at the repo. It's a bad idea to be adding passwords to an exception, so I would simply not do that instead of using that library.

I think rather than deciding to support Destructurama, we should perhaps think about adding some extensibility that allows you to decide whether you want to log a property or not e.g.

```cs
bool CanLogProperty(Type type, string propertyName);
```

But not sure if this is useful, you are the first person to ask for a feature like this and like I say, adding secrets to exceptions is a bad idea.

**Comment by luizbon** [comment]
Fair point to argument.
In my case is not about secrets, but having Personal Identifiable Information (PII) data on custom exceptions.
For example, an exception that captures a request which posted PII data.

**Comment by RehanSaeed** [comment]
Would it be possible to remove that data from the exceptions in the first place?

**Comment by luizbon** [comment]
Yes it is, but it'll be nicer to have the whole logging pipeline respecting the current applied enrichers.

**Comment by RehanSaeed** [comment]
Thoughts @krajek?

**Comment by krajek** [comment]
I agree @RehanSaeed.
The problem seems to be out of the domain of the library.
I do not know the details, so I may miss something, but it seems that exception should only contain some identifier (GUID for example) that would allow an authorized actor to reach for PII if necessary (debugging or audit purposes), secured by proper authorization. 

@luizbon  Alternatively, you could write your own destructurer for particular exception types. Maybe that's viable in your case.

**Comment by luizbon** [comment]
Fair enough, the downside of using identifiers is that it's required to have code to load the data on the exception handler that needs the data. But is understandable to have it.

My suggestion was related to the library respect the current enrichers configured on Serilog pipeline when destructing the exception. Probably I wasn't clear of this when opened the issue.
I'll close this issue as it's not relevant to the library.
Thanks
