### ISSUE TITLE
Web/Htttp exceptions

### ISSUE THREAD

**Issue by mdissel** [RehanSaeed/Serilog.Exceptions#41]
Is there a reason why web/http exceptions types are not added?

**Comment by RehanSaeed** [comment]
Firstly, they are still handled and logged but using reflection. Serilog.Exceptions handles all basic exceptions in the base class library in .NET Core. We can't add all exceptions in all NuGet packages because that would add a lot of bloat to your application.

Long term, my plan is to add additional packages to this project that would handle exceptions in other packages without using reflection. These packages would contain the necessary destructurers to do this.

Feel free to submit a PR, if you would like to add such a feature.

**Comment by mdissel** [comment]
I guess when switching to fastmember (or other reflection strategy) the overhead will be minimal

**Comment by RehanSaeed** [comment]
There is currently a PR for fastmember (I was not aware of the library, so feel free to comment on the PR, the more eyes on it the better). The benchmark shows a slight improvement.

**Comment by krajek** [comment]
@mdissel do you expect any work on our side? It seems that your needs are met by the automatic reflection destructurer, but I am asking just to be sure.

**Comment by mdissel** [comment]
reflection is ok for now.
