### ISSUE TITLE
Failing build

### ISSUE THREAD

**Issue by krajek** [RehanSaeed/Serilog.Exceptions#43]
@RehanSaeed you must have noticed that build is failing. Did you try to fix it? Do you any idea why it started failing in the first place? 
I would suggest fixing the problem before releasing next major version.

**Comment by RehanSaeed** [comment]
I was ignoring Travis CI because the Windows build fails on Linux even though Mono is installed (It used to work in project.json). There is an open issue about it and my understanding is that it will probably get fixed in 2.1.

Check the AppVeyor build [history](https://ci.appveyor.com/project/RehanSaeed/serilog-exceptions/history). Looks like your PR broke the build. I must have missed it.

**Comment by RehanSaeed** [comment]
BTW, I also have a Circle CI build that I have not added to ReadMe. I've been experimenting with using it as a replacement for Travis CI because Travis is slow to start a build and slow to run too because they install .NET Core from scratch each time. Circle CI uses Docker.

**Comment by krajek** [comment]
You are right, the build was passing before I started contributing regularly, I will investigate the issue before the major release.

**Comment by krajek** [comment]
Do you know any way I could re-run build for some historical commit? It would help a lot in the diagnosis of the problem.

**Comment by RehanSaeed** [comment]
FYI, AppVeyor and Travis CI just run Cake build (I highly recommend it). You can just run that yourself on an old commit.

Anyway, I merged your PR. Thanks again.
