### ISSUE TITLE
Please update version of System.Data.SqlClient in Serilog.Exceptions.SqlServer

### ISSUE THREAD

**Issue by Banner-Keith** [RehanSaeed/Serilog.Exceptions#830]
### Describe the bug

System.Data.SqlClient 4.8.1 has a high and a moderate security vulnerability. Please update to [4.8.6](https://www.nuget.org/packages/System.Data.SqlClient/4.8.6)

There are no breaking changes so it should be a quick update.

### Steps to reproduce

See vulnerability here: https://www.nuget.org/packages/System.Data.SqlClient/4.8.1

### Expected behaviour

No vulnerable dependencies.

**Comment by alexdresko** [comment]
Also, I'm getting an error `Could not load type 'SqlGuidCaster' from assembly 'System.Data.SqlClient, Version=4.6.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.'` which appears to be related to the version of System.Data.SqlClient being referenced. See https://github.com/dotnet/SqlClient/issues/1930. 

I removed Serilog.Exceptions.SqlServer from my project and the error went away.
